unit res2goResources;

{$mode objfpc}{$H+}

interface



resourceString
  rsMsgTransformFile = 'Transform file: %s ';
  rsAutomaticallyGeneratedByTheRes2go = 'Automatically generated by the res2go.';
  rsAutomaticallyGeneratedByTheRes2goDoNotEdit = 'Automatically generated by the res2go, do not edit.';
  rsComponentIsNotSupported = '"%s:%s" is not supported.';
  rsComponentMustBeCapitalizedFirstToBeExported = '"%s:%s" must be capitalized first to be exported.';
  rsRegisterFormResources = 'Register Form Resources';

  // options frame
  rsEnabledConvert = 'Enabled Convert';
  rsUseOriginalFileName = 'Use Original File Name';
  rsOutputPath = 'Output Path:';
  rsOutputPathEg = 'eg:  /code';

implementation

end.

