//----------------------------------------
//
// Copyright © ying32. All Rights Reserved.
//
// Licensed under Lazarus.modifiedLGPL
//
//----------------------------------------
unit res2goResources;

{$mode objfpc}{$H+}

interface

resourceString
  rsMsgTransformFile = 'Transform file: %s ';
  rsAutomaticallyGeneratedByTheRes2go = 'Automatically generated by the res2go IDE plug-in.';
  rsAutomaticallyGeneratedByTheRes2goDoNotEdit = 'Automatically generated by the res2go IDE plug-in, do not edit.';
  rsComponentIsNotSupported = '"%s:%s" is not supported.';
  rsComponentMustBeCapitalizedFirstToBeExported = '"%s:%s" must be capitalized first to be exported.';
  rsRegisterFormResources = 'Register Form Resources';

  // options frame
  rsEnabledConvert = 'Enabled Convert';
  rsUseOriginalFileName = 'Use Original File Name';
  rsSaveGfmFile = 'Save gfm File';
  rsOutputPath = 'Output Path:';
  rsOutputPathEg = 'eg:  "code" or "$Path($ProjectFile())code" or "C:\LzUI" ';
  rsOutputLang = 'Output Lang:';
  rsPackageName = 'Package Name:';
  rsUseDefaultWinAppRes = 'Use Default winappres';
  rsGoUseTempdll = 'Use "tempdll"';
  rschkGoEnabledFinalizerOn = 'Enabled "finalizerOn"';
  rsGoTags = 'Tags:';
  rsDividerBevel1 = 'For Golang';

implementation

end.

